import {
  MicrophoneIcon,
  SearchIcon,
  ViewGridIcon,
} from '@heroicons/react/solid';
import Head from 'next/head';
import Image from 'next/image';
import Avatar from '../components/Avatar';
import Button from '../components/Button';
import Footer from '../components/Footer';
import Languages from '../components/languages';
import { useRouter } from 'next/router';
import { useRef } from 'react';

export default function Home() {
  const router = useRouter();
  const searchRef = useRef();

  const handleSearch = (e) => {
    e.preventDefault();
    const term = searchRef.current.value;

    if (!term) return;
    router.push(`/search?term=${term}`);
  };

  return (
    <div>
      <Head>
        <title>dubem's google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='w-full h-[100vh] flex flex-col justify-between'>
        <header className='flex items-center space-x-2 text-[#3b3b3b] w-full justify-end text-sm px-5 py-2 '>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>
          <ViewGridIcon className='h-9 p-1 cursor-pointer rounded-full hover:bg-[#cccccc]' />
          <Avatar url='https://lh3.googleusercontent.com/ogw/ADea4I4EonhM2gzrG1M4VvysYOwLowdOdSbjeImSzylWdA=s32-c-mo' />
        </header>

        <form className='flex flex-col items-center justify-center  px-4 flex-grow'>
          <Image
            src='https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
            width={250}
            height={84}
          />
          <div className='flex border border-[#dadada] rounded-full w-full p-3 items-center text-[#B8BEC6] sm:max-w-xl  lg:max-w-xl max-w-md hover:shadow-lg focus-within:shadow-lg px-3 mt-3'>
            <SearchIcon className='h-6 mr-3' />
            <input
              type='text'
              ref={searchRef}
              className='bg-transparent flex-grow outline-none text-black'
            />
            <MicrophoneIcon className='h-6 cursor-pointer ml-2' />
          </div>
          <div className='flex space-x-4 py-4' onClick={handleSearch}>
            <Button btnText='Google Search' />
            <Button btnText={`I'm Feeling Lucky`} />
          </div>
          <div className='flex space-x-2 items-center text-sm text-[#353739]'>
            <p>Google offered in:</p>
            <Languages />
          </div>
        </form>

        <Footer />
      </main>
    </div>
  );
}
