import React from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { API_KEY, CONTEXT_KEY } from '../keys';
import Header from '../components/Header';
import SearchResults from '../components/SearchResults';
import Response from '../Response';

const Search = ({ results }) => {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>{router.query.term} - Google Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />

        <SearchResults results={results} />
      </main>
    </div>
  );
};

export default Search;

export const getServerSideProps = async (context) => {
  const dummyData = true;
  const startIndex = context.query.satrt || '0';

  const data = dummyData
    ? Response
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONTEXT_KEY}&q=${context.query.term}&start=${startIndex}`
      ).then((response) => response.json());

  return {
    props: {
      results: data,
    },
  };
};
